export const meta = {
  name: 'nj-deals-B',
  description: 'Workstream B: NJ industrial acquisitions 2019-2024 from trade press, broker releases and REIT disclosures; agents split by year, by geography and by REIT group',
  phases: [{ title: 'Deals', detail: 'one agent per slice; each writes a JSONL part file' }],
}

const RULES = `You are a research subagent for a New Jersey industrial real-estate broker (tenant-rep / investment sales). Your output is DATA that will be machine-joined to a local property graph; structure matters more than prose.

TOOLS / NETWORK: Use the WebSearch tool (if it is not loaded, load it with ToolSearch query "select:WebSearch"). WebFetch, curl and every direct page fetch are BLOCKED by this environment's network egress policy - do not use them (if you try once and see EGRESS_BLOCKED, do not retry). WebSearch returns result URLs plus excerpts/summaries of page content; extract facts ONLY from what those results actually state, and attribute each fact to the result URL whose title/content carries it. Use mode "extended" for deal-specific, older or niche queries and "standard" for simple lookups. Use the allowed_domains parameter to sweep one publication at a time (e.g. ["roi-nj.com"], ["njbiz.com"], ["re-nj.com"], ["commercialobserver.com"], ["globest.com"], ["therealdeal.com"], ["bisnow.com"], ["rebusinessonline.com"], ["connectcre.com"], ["traded.co"], ["cushmanwakefield.com"], ["cbre.com"], ["jll.com"], ["colliers.com"], ["nmrk.com"], ["avisonyoung.com"], ["naihanson.com"], ["kislakrealty.com"], ["lee-associates.com"], ["marcusmillichap.com"], ["svn.com"], ["prnewswire.com"], ["businesswire.com"], ["sec.gov"]). Vary wording across queries. Your WebSearch call cap is stated at the end of this prompt and is a hard limit. Write a first version of your output file about halfway through and overwrite it with the complete version at the end.

HARD RULES:
1. Public free web only. No logins, accounts, forms, CAPTCHAs, paywalls. Never contact anyone.
2. Every row needs a source_url that appeared in your search results and supports the row. If you cannot source a fact, leave the cell empty (""). Never guess. Never invent names.
3. confidence: "high" = official press release (buyer, seller, REIT or brokerage) or SEC filing; "med" = trade-press report; "low" = aggregator (traded.co, LoopNet-type) or secondhand mention.
4. Geography in scope: NJ counties Bergen, Burlington, Essex, Hudson, Mercer, Middlesex, Monmouth, Morris, Passaic, Somerset, Union ONLY. Out of scope (skip): Camden, Gloucester, Salem, Cumberland, Atlantic, Cape May, Ocean, Warren, Sussex, Hunterdon, and anything outside NJ.
5. Product in scope: industrial, warehouse/distribution, flex, IOS (industrial outdoor storage), truck terminals/truck parking, cold storage, small-bay/multi-tenant industrial, industrial land (incl. land bought for warehouse development). Skip pure office, retail, multifamily, self-storage, data centers. Skip leases (sales only). Record big deals too, but make sure small ones (under 250,000 SF) are not missed.
6. Time window: ONLY sales announced or closed 2019-01-01 through 2024-12-31. Skip anything dated 2025 or 2026 (already collected locally).
7. The six call-list buyers (CenterPoint, Terreno, Cabot, Sitex, Elberon, Kurv / Bridge Industrial) are lower priority: record their deals when you meet them, but do not run dedicated searches for them.
8. Numbers (sf, acres, price, price_psf, cap_rate, loan_amount, year_built) are plain numbers without $, commas, "SF" or "%": 18500000 not "$18.5M"; cap_rate 5.75 for 5.75%; occupancy_at_sale as a percent number (100 for fully leased, 0 for vacant) or "". price_psf: compute only when both price and sf are stated (round to whole dollars) and add "psf computed" to notes. Dates: YYYY-MM-DD; if the day is unknown YYYY-MM; if only the year, YYYY. county: fill from the town (each NJ town is in exactly one county).
9. name keys: buyer_name_key / seller_name_key = the name in UPPERCASE with punctuation removed and the tokens LLC, INC, LP, CORP, THE removed, single-spaced.
10. One row per property sold. For portfolio deals: one row per property when the addresses are listed (deal_type="portfolio", portfolio_context like "part of 4-building, 256,000 SF, $XXM Carlstadt/East Rutherford portfolio") PLUS one summary row with address="PORTFOLIO: <n> buildings", town = main town(s), sf = total, price = total. If the article names the buying entity ("an affiliate of X", "XYZ Carlstadt LLC", "X Industrial Fund III") put the entity name in buyer_spv_named and the sponsor in buyer. Brokers: "Listing: Firm (Name, Name); Procuring: Firm (Name)" or just the firm(s) if roles are unclear. Lender/loan_amount only if the article states acquisition financing.
11. OUTPUT: write ONE JSON object per line (JSONL, no wrapping array) to the exact absolute path given below using the Write tool. Use exactly the field names listed; include every field in every row ("" when unknown). Write the file even if you found little. Then return the structured summary requested. Your final answer is the structured output only - no prose report.`

const B_FIELDS = `date, address, town, county, buyer, buyer_name_key, buyer_parent, buyer_spv_named, seller, seller_name_key, seller_parent, sf, acres, price, price_psf, cap_rate, property_type (industrial | warehouse | flex | IOS | truck terminal | cold storage | small-bay | land | other), year_built, occupancy_at_sale, tenant, lender, loan_amount, brokers, deal_type (sale | sale-leaseback | portfolio | land | JV | ground lease), portfolio_context, source_url, source_date, confidence (high | med | low), notes`

const TOWNS = 'Carlstadt, Moonachie, Teterboro, Little Ferry, South Hackensack, Hackensack, Saddle Brook, Elmwood Park, Lodi, Garfield, Mahwah, Englewood, Northvale, Norwood, Ridgefield, East Rutherford, Lyndhurst, Wood-Ridge, Hasbrouck Heights, Secaucus, Kearny, South Kearny, Harrison, North Bergen, Jersey City, Bayonne, Newark, Irvington, Orange, Bloomfield, Belleville, Nutley, Fairfield, West Caldwell, Livingston, Elizabeth, Linden, Hillside, Union, Kenilworth, Cranford, Rahway, Springfield, Roselle, Clark, Clifton, Passaic, Paterson, Totowa, Wayne, Little Falls, Hawthorne, Edison, Piscataway, South Plainfield, New Brunswick, North Brunswick, South Brunswick, Cranbury, Monroe, Dayton, Jamesburg, Sayreville, Old Bridge, Woodbridge, Avenel, Carteret, Perth Amboy, Metuchen, Middlesex Borough, Somerset, Franklin Township, Branchburg, Bridgewater, Hillsborough, Bound Brook, Warren, Parsippany, Rockaway, Dover, Pine Brook, Montville, Whippany, Hanover, Randolph, Mount Olive, Boonton, Denville, East Hanover, Florham Park, Hamilton, Robbinsville, Ewing, Trenton, Lawrenceville, West Windsor, East Windsor, Freehold, Neptune, Wall, Farmingdale, Howell, Eatontown, Tinton Falls, Marlboro, Matawan, Keyport, Burlington Township, Florence, Bordentown, Mount Laurel, Moorestown, Cinnaminson, Delanco, Westampton, Mount Holly, Lumberton, Evesham/Marlton'

const YEAR_TASK = (year) => `TASK (Workstream B - NJ industrial acquisitions announced in ${year}). Sweep the trade press and brokerage press releases for every in-scope NJ industrial SALE dated in ${year}: ROI-NJ, NJBIZ, Real Estate NJ (re-nj.com, incl. its monthly flipbook pages), NJ.com / NorthJersey.com business pages, Commercial Observer, GlobeSt, The Real Deal (Tri-State), Bisnow New Jersey, REBusinessOnline (Northeast), Connect CRE, Traded.co (NJ), CoStar News free pages, PRNewswire / BusinessWire broker releases, and the newsroom pages of Cushman & Wakefield, CBRE, JLL, Colliers, Newmark, Avison Young, NAI James E. Hanson, NAI DiLeo-Bram, NAI Mertz, Kislak, Lee & Associates NJ, Marcus & Millichap, SVN, Savills, Meridian Capital, Bussel Realty, Cronheim, Greiner-Maltz, Sheldon Gross, Weichert Commercial, Resource Realty, Zimmel Associates, Team Resources, Transwestern, Hilco Real Estate. Sweep publication by publication with allowed_domains and queries like "industrial sold ${year}", "warehouse acquires ${year}", "sells for" "square-foot" ${year}, "industrial" "New Jersey" "acquisition" ${year}, and then sweep by town: "<town> industrial building sold ${year}" / "<town> warehouse sells ${year}" for the main industrial towns: ${TOWNS}. Also search "sale-leaseback New Jersey ${year}", "industrial outdoor storage New Jersey sold ${year}", "truck terminal New Jersey sold ${year}", "cold storage New Jersey acquired ${year}", "industrial land New Jersey acquired ${year} warehouse development", "multi-tenant industrial portfolio New Jersey ${year}". Capture every distinct property; aim for 60+ rows if coverage exists.`

const GEO_TASK = (label, towns) => `TASK (Workstream B - NJ industrial acquisitions 2019-2024, geographic sweep: ${label}). For EACH town listed, run searches across the years 2019-2024 for industrial sales: "<town> NJ industrial building sold", "<town> warehouse sells for", "<town> industrial acquires", "<town> NJ "square-foot" industrial sale", "<town> flex building sold", "<town> industrial land acquired", and also with a year appended (2019, 2020, 2021, 2022, 2023, 2024), and with the main publication domains via allowed_domains (roi-nj.com, njbiz.com, re-nj.com, commercialobserver.com, globest.com, therealdeal.com, bisnow.com, rebusinessonline.com, traded.co, connectcre.com, prnewswire.com, cushmanwakefield.com, cbre.com, jll.com, colliers.com, nmrk.com, naihanson.com, kislakrealty.com). Towns: ${towns}. Capture every distinct property sale 2019-2024 you can source; aim for 60+ rows if coverage exists. Include IOS yards, truck terminals, cold storage and industrial land.`

const REIT_TASK = (label, names) => `TASK (Workstream B - NJ industrial acquisitions 2019-2024 disclosed by ${label}). For each company listed, find its NJ industrial acquisitions 2019-2024 from its own press releases (quarterly "acquisition activity" releases, individual deal announcements), investor supplementals, 10-K / 10-Q text and Schedule III property lists on sec.gov (use allowed_domains ["sec.gov"] with queries such as "<company> 10-K Schedule III <NJ town>"), plus trade-press coverage of those deals. Companies: ${names}. Search patterns: "<company> acquires New Jersey industrial <year>", "<company> acquisition <town> New Jersey", "<company> fourth quarter acquisition activity <year> New Jersey", "<company> sale-leaseback New Jersey". Record the acquiring subsidiary name in buyer_spv_named when a filing or article names it. One row per property; aim for as many as the disclosures support.`

const ALL_SLICES = [
  { key: 'B_year_2019', task: YEAR_TASK(2019) },
  { key: 'B_year_2020', task: YEAR_TASK(2020) },
  { key: 'B_year_2021', task: YEAR_TASK(2021) },
  { key: 'B_year_2022', task: YEAR_TASK(2022) },
  { key: 'B_year_2023', task: YEAR_TASK(2023) },
  { key: 'B_year_2024', task: YEAR_TASK(2024) },
  { key: 'B_geo_bergen', task: GEO_TASK('Bergen County', 'Carlstadt, Moonachie, Teterboro, Little Ferry, South Hackensack, Hackensack, Saddle Brook, Elmwood Park, Lodi, Garfield, Mahwah, Englewood, Northvale, Norwood, Ridgefield, Fairview, East Rutherford, Lyndhurst, Wood-Ridge, Hasbrouck Heights, Paramus, Rochelle Park, Fair Lawn, Oakland, Franklin Lakes, Allendale, Ramsey, Upper Saddle River, Montvale, Park Ridge, Westwood, Emerson, Oradell, Bergenfield, Dumont, Cresskill, Palisades Park, Edgewater') },
  { key: 'B_geo_hudson_essex', task: GEO_TASK('Hudson and Essex Counties', 'Secaucus, Kearny, South Kearny, Harrison, North Bergen, Jersey City, Bayonne, Newark (Ironbound, Port Newark, Doremus Avenue, Frelinghuysen Avenue, Delancy Street), Irvington, East Orange, Orange, West Orange, Bloomfield, Belleville, Nutley, Fairfield, West Caldwell, Caldwell, Livingston, Cedar Grove, Verona, Montclair, Maplewood, Millburn') },
  { key: 'B_geo_union_passaic', task: GEO_TASK('Union and Passaic Counties', 'Elizabeth, Linden, Hillside, Union Township, Kenilworth, Cranford, Rahway, Springfield, Roselle, Roselle Park, Garwood, Clark, Westfield, Scotch Plains, Plainfield, Berkeley Heights, New Providence, Summit, Clifton, Passaic, Paterson, Totowa, Wayne, Little Falls, Woodland Park, Hawthorne, Haledon, Prospect Park, Pompton Lakes, Wanaque, Bloomingdale') },
  { key: 'B_geo_middlesex', task: GEO_TASK('Middlesex County', 'Edison, Piscataway, South Plainfield, New Brunswick, North Brunswick, South Brunswick, Cranbury, Monroe Township, Dayton, Jamesburg, Sayreville, Old Bridge, Woodbridge, Avenel, Iselin, Keasbey, Port Reading, Sewaren, Carteret, Perth Amboy, Metuchen, Middlesex Borough, Dunellen, East Brunswick, Spotswood, Helmetta, Milltown, Highland Park, South Amboy, South River, Plainsboro') },
  { key: 'B_geo_somerset_morris', task: GEO_TASK('Somerset and Morris Counties', 'Somerset, Franklin Township, Branchburg, Bridgewater, Hillsborough, Bound Brook, South Bound Brook, Manville, Warren, Bernards/Basking Ridge, Bernardsville, Somerville, Raritan, Green Brook, Watchung, Montgomery, Parsippany, Rockaway, Dover, Wharton, Pine Brook, Montville, Whippany, Hanover, Cedar Knolls, Randolph, Mount Olive, Flanders, Budd Lake, Boonton, Denville, East Hanover, Florham Park, Morris Plains, Morristown, Kenvil, Ledgewood, Roxbury, Riverdale, Butler, Lincoln Park, Pequannock, Mount Arlington') },
  { key: 'B_geo_mercer_monmouth_burlington', task: GEO_TASK('Mercer, Monmouth and Burlington Counties', 'Hamilton, Robbinsville, Ewing, Trenton, Lawrenceville, West Windsor, East Windsor, Hightstown, Princeton, Pennington, Hopewell, Freehold, Neptune, Wall, Farmingdale, Howell, Eatontown, Tinton Falls, Marlboro, Matawan, Keyport, Aberdeen, Red Bank, Shrewsbury, Oceanport, Long Branch, Manalapan, Englishtown, Millstone, Burlington Township, Burlington City, Florence, Bordentown, Mount Laurel, Moorestown, Cinnaminson, Delanco, Delran, Riverside, Westampton, Mount Holly, Lumberton, Evesham, Marlton, Pemberton, Medford, Southampton, Mansfield, Columbus, Springfield Township, Edgewater Park, Willingboro, Palmyra, Riverton, Maple Shade') },
  { key: 'B_reit_industrial', task: REIT_TASK('industrial REITs and non-traded industrial REITs', 'Prologis (and Duke Realty 2019-2022); STAG Industrial; First Industrial Realty Trust; LXP Industrial Trust (Lexington Realty); Plymouth Industrial REIT; Industrial Logistics Properties Trust (ILPT) and Monmouth Real Estate Investment Corp; Dream Industrial REIT; Granite REIT; Ares Industrial REIT / Black Creek Industrial REIT IV / Industrial Property Trust; JLL Income Property Trust; Nuveen Global Cities REIT; BREIT; Starwood REIT; Hines Global Income Trust; KKR Real Estate Select Trust; Peakstone Realty Trust / Griffin Realty; Rexford and EastGroup (only to confirm they have no NJ deals); Terreno Realty (quick pass via its acquisition press releases only - it is on the broker call list).') },
  { key: 'B_reit_netlease_cold', task: REIT_TASK('net-lease, sale-leaseback, cannabis and cold-storage owners', 'W. P. Carey; Realty Income (incl. Spirit Realty); Broadstone Net Lease; Essential Properties Realty Trust; Gladstone Commercial; One Liberty Properties; Four Springs Capital Trust; Global Net Lease; NETSTREIT; Alpine Income Property Trust; Modiv Industrial; Blue Owl Net Lease / Oak Street; LCN Capital Partners; STORE Capital; Innovative Industrial Properties; NewLake Capital; Chicago Atlantic; Power REIT; Americold; Lineage; Vertical Cold Storage; Karis Cold; RL Cold; Iron Mountain; Getty Realty (only if an industrial/truck property in NJ).') },
]

const wanted = (args && args.slices) || ALL_SLICES.map(s => s.key)
const SLICES = ALL_SLICES.filter(s => wanted.includes(s.key))

const B_SCHEMA = {
  type: 'object',
  properties: {
    part_file: { type: 'string' },
    rows_written: { type: 'integer' },
    portfolio_rows: { type: 'integer' },
    buyers_seen: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, count: { type: 'integer' } }, required: ['name', 'count'] }, description: 'distinct buyers in your rows with the number of properties each bought' },
    searches_run: { type: 'integer' },
    blocked: { type: 'array', items: { type: 'string' } },
    thin_coverage: { type: 'array', items: { type: 'string' }, description: 'publications, towns or years where you found little' },
    notes: { type: 'string' },
  },
  required: ['part_file', 'rows_written', 'portfolio_rows', 'buyers_seen', 'searches_run', 'blocked', 'thin_coverage', 'notes'],
}

function promptForBase(s) {
  const path = '/home/user/cladue/buyers_research/parts/B_deals/' + s.key + '.jsonl'
  return RULES + '\n\n' + s.task + '\n\nOUTPUT FILE (absolute path, JSONL): ' + path + '\nFIELDS (every row, in this order): ' + B_FIELDS +
    '\n\nWhen done, return the structured summary: part_file, rows_written, portfolio_rows, buyers_seen (distinct buyer names with counts), searches_run, blocked, thin_coverage, notes (one paragraph: what you searched, what was thin).'
}


// --- budget / continuation block appended to every agent prompt (args.search_cap, args.leads[key]) ---
function extra(key) {
  const cap = (args && args.search_cap) || 25
  const leads = (args && args.leads && args.leads[key]) || ''
  return '\n\nSEARCH BUDGET: you may run AT MOST ' + cap + ' WebSearch calls in total - count them. The pool is shared by every agent in this turn and exceeding your share starves the others. Plan your full query list first, run the highest-value queries first, and stop when you reach the cap or when WebSearch replies that the budget is used up - then Write your file immediately.' +
    '\n\nCONTINUING PRIOR WORK: if the output file already exists, Read it first and keep every existing row (correct only obvious errors); your final Write must contain the union of existing and new rows, deduped. Do not re-search items that already have complete rows unless they appear in the leads below.' +
    (leads ? '\n\nLEADS / GAPS FROM THE PREVIOUS PASS (start with these): ' + leads : '')
}
function promptFor(x) { return promptForBase(x) + extra(x.key) }

phase('Deals')
log('Workstream B: ' + SLICES.length + ' slices')
const results = await parallel(SLICES.map(s => () => agent(promptFor(s), { label: 'B:' + s.key, phase: 'Deals', schema: B_SCHEMA })))
const out = results.filter(Boolean)
log('B done: ' + out.reduce((n, r) => n + (r.rows_written || 0), 0) + ' rows across ' + out.length + ' parts')
return out